### ISSUE TITLE
[BUG] Docs example for `griffin ssm config get` contain non-existent flag

### ISSUE THREAD

**Issue by agrove-spoton** [griffin-cli/griffin-cli#40]
**Describe the bug**
The readme usage example for `griffin ssm config get` contains a --store flag that the command doesn't 

**To Reproduce**
Read the readme

**Expected behavior**
The flags and examples should be consistent.

**Desktop (please complete the following information):**
N/A

**CLI information**
0.4.0

**Additional context**
N/A

**Comment by c1moore** [comment]
Thanks for the report, this should be resolved in the next patch release.  It'll likely go out in the next 24 hours.

**Comment by c1moore** [comment]
This has been resolved in [v0.4.1](https://github.com/griffin-cli/griffin-cli/releases/tag/v0.4.1) with PR #42.
