### ISSUE TITLE
[FEATURE] add option to specify config directory from commands

### ISSUE THREAD

**Issue by agrove-spoton** [griffin-cli/griffin-cli#41]
It would be convenient to be able to specify the config directory from the running command instead of having to run the command from that directory.  Specifically this would be useful on the `exec` command which is used in loading the application.  It would also be nice to have this feature on the export and SSM commands as well.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Config directory flag/option

**Describe alternatives you've considered**
Changing directories works but adds clutter to the application load script

**Additional context**
N/A

**Comment by c1moore** [comment]
This makes sense, though, I'll likely implement as a global flag since most/all commands use the config file.  I'm thinking `--cwd` and`-c` as a shorthand (assuming that won't cause conflicts with existing commands) makes sense.  Any thoughts?

**Comment by agrove-spoton** [comment]
That should work fine. 👍

**Comment by c1moore** [comment]
This should be resolved as of [v0.5.0](https://github.com/griffin-cli/griffin-cli/releases/tag/v0.5.0).  Due to conflicts with existing flags, I didn't add a shorthand (`-c`) for this flag.
