### ISSUE TITLE
[FEATURE] SSM commands should let you specify a named AWS profile to run against

### ISSUE THREAD

**Issue by agrove-spoton** [griffin-cli/griffin-cli#46]
**Is your feature request related to a problem? Please describe.**
It seems that the SSM commands only work against the default AWS profile.  It would be nice if I didn't have to reconfigure my AWS profiles to run these commands on a specific account.

**Describe the solution you'd like**
It would be nice to have and AWS profile option for each of the SSM commands

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by c1moore** [comment]
You should be able to specify the `AWS_PROFILE` environment variable to tell the AWS SDK what profile you'd like to share.  For example:

```sh
AWS_PROFILE=prod griffin ssm history -n /path/var
```

I might add an example of this to the README.

In terms of adding it to the command, I'd rather leave that out and leverage AWS's default behavior unless there's a use case the above doesn't fill.

**Comment by agrove-spoton** [comment]
That's a good point and a better solution.  And yes plz add an example to the README.
